### ISSUE TITLE
if comments another language as english - panic

### ISSUE THREAD

**Issue by sardigital** [hatamiarash7/Mikrotik-Exporter#13]

**Comment by hatamiarash7** [comment]
It's like #1 and #2. I'm working on it.

**Comment by sardigital** [comment]
# ./mikrotik-exporter_linux_amd64 --address=172.16.1.220 --device=mik-01 --user=prometheus --password=cmUbhlKfvbT6L-e_gUjQAAgN2I
{"level":"info","msg":"Welcome to Mikrotik Prometheus Exporter","time":"2020-10-15T06:27:30+03:00"}
{"level":"info","msg":"Version: 1.2.3","time":"2020-10-15T06:27:30+03:00"}
{"level":"info","msg":"Setting up collector for devices","numDevices":1,"time":"2020-10-15T06:27:30+03:00"}
{"level":"info","msg":"Listening on :9436","time":"2020-10-15T06:27:30+03:00"}
panic: label value "\xdd\xed\xe3\xe5\xeb\xfc\xf1" is not valid UTF-8

goroutine 23 [running]:
github.com/prometheus/client_golang/prometheus.MustNewConstMetric(...)
        /home/runner/go/pkg/mod/github.com/prometheus/client_golang@v1.2.1/prometheus/value.go:102
mikrotik-exporter/collector.(*interfaceCollector).collectMetricForProperty(0xc0000f8140, 0x9a5f2c, 0x7, 0xc000025770, 0x6, 0xc000025790, 0x7, 0xc00006b900, 0xc00000d7e0)
        /home/runner/work/Mikrotik-Exporter/Mikrotik-Exporter/collector/interface_collector.go:88 +0x70e
mikrotik-exporter/collector.(*interfaceCollector).collectForStat(0xc0000f8140, 0xc00006b900, 0xc00000d7e0)
        /home/runner/work/Mikrotik-Exporter/Mikrotik-Exporter/collector/interface_collector.go:70 +0x186
mikrotik-exporter/collector.(*interfaceCollector).collect(0xc0000f8140, 0xc00000d7e0, 0xc000060ea0, 0x0)
        /home/runner/work/Mikrotik-Exporter/Mikrotik-Exporter/collector/interface_collector.go:46 +0x86
mikrotik-exporter/collector.(*collector).connectAndCollect(0xc0000fe500, 0xc000126580, 0xc00011a3c0, 0x0, 0x0)
        /home/runner/work/Mikrotik-Exporter/Mikrotik-Exporter/collector/collector.go:320 +0x3a9
mikrotik-exporter/collector.(*collector).collectForDevice(0xc0000fe500, 0x7ffdc89707cc, 0x6, 0x7ffdc89707b6, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/work/Mikrotik-Exporter/Mikrotik-Exporter/collector/collector.go:291 +0xdc
mikrotik-exporter/collector.(*collector).Collect.func1(0xc0000fe500, 0xc00011a3c0, 0xc000108530, 0x7ffdc89707cc, 0x6, 0x7ffdc89707b6, 0xc, 0x0, 0x0, 0x0, ...)
        /home/runner/work/Mikrotik-Exporter/Mikrotik-Exporter/collector/collector.go:256 +0x7d
created by mikrotik-exporter/collector.(*collector).Collect
        /home/runner/work/Mikrotik-Exporter/Mikrotik-Exporter/collector/collector.go:255 +0x2f2

**Comment by Rid-lin** [comment]
I faced the same problem today.
But in my case, panic is not given by comments (which can be changed to transliteration), but by the name of the PC that has non-Latin characters in the hostname. In Winbox, the hostname looks like (User-ЏЉ), in WebFig - (User-), but in fact the hostname contains Cyrillic characters and should look like (User-ПК).

```
mikrotik_exporter --config-file=/etc/mikrotik_exporter/config.yml
{"level":"info","msg":"Welcome to Mikrotik Prometheus Exporter","time":"2020-11-11T20:43:38+05:00"}
{"level":"info","msg":"Version: 1.2.4","time":"2020-11-11T20:43:38+05:00"}
{"level":"info","msg":"Setting up collector for devices","numDevices":1,"time":"2020-11-11T20:43:38+05:00"}
{"level":"info","msg":"Listening on :9436","time":"2020-11-11T20:43:38+05:00"}
panic: label value "User-\x8f\x8a" is not valid UTF-8

goroutine 25 [running]:
github.com/prometheus/client_golang/prometheus.MustNewConstMetric(...)
        /home/runner/go/pkg/mod/github.com/prometheus/client_golang@v1.2.1/prometheus/value.go:102
mikrotik-exporter/collector.(*dhcpLeaseCollector).collectMetric(0xc000085fa0, 0xc0001b25a0, 0xc0001d5940)
        /home/runner/work/Mikrotik-Exporter/Mikrotik-Exporter/collector/dhcp_lease_collector.go:69 +0x4bd
mikrotik-exporter/collector.(*dhcpLeaseCollector).collect(0xc000085fa0, 0xc0001b25a0, 0x0, 0x0)
        /home/runner/work/Mikrotik-Exporter/Mikrotik-Exporter/collector/dhcp_lease_collector.go:41 +0x86
mikrotik-exporter/collector.(*collector).connectAndCollect(0xc000068f00, 0xc0000dea00, 0xc000094ea0, 0x0, 0x0)
        /home/runner/work/Mikrotik-Exporter/Mikrotik-Exporter/collector/collector.go:327 +0x3a9
mikrotik-exporter/collector.(*collector).collectForDevice(0xc000068f00, 0xc00008e950, 0x7, 0xc00008e970, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/work/Mikrotik-Exporter/Mikrotik-Exporter/collector/collector.go:298 +0xdc
mikrotik-exporter/collector.(*collector).Collect.func1(0xc000068f00, 0xc000094ea0, 0xc00008f3d0, 0xc00008e950, 0x7, 0xc00008e970, 0xc, 0x0, 0x0, 0x0, ...)
        /home/runner/work/Mikrotik-Exporter/Mikrotik-Exporter/collector/collector.go:263 +0x7d
created by mikrotik-exporter/collector.(*collector).Collect
        /home/runner/work/Mikrotik-Exporter/Mikrotik-Exporter/collector/collector.go:262 +0x2f2
```

**Comment by hatamiarash7** [comment]
@Rid-lin @sardigital There is a **UTF-8** problem with the Prometheus exporter library. I asked them and they ignored to fix that. So I have to think about this problem myself

**Comment by Rid-lin** [comment]
To support Cyrillic (WindowsCirillic-CP866), I rewrote the function like this

```
func (c *dhcpLeaseCollector) collectMetric(ctx *collectorContext, re *proto.Sentence) {
	v := 1.0

	activemacaddress := re.Map["active-mac-address"]
	status := re.Map["status"]
	expiresafter := re.Map["expires-after"]
	activeaddress := re.Map["active-address"]
	hostname := re.Map["host-name"]
	decoder := charmap.CodePage866.NewDecoder()
	reader := decoder.Reader(strings.NewReader(hostname))
	b, err := ioutil.ReadAll(reader)
	if err != nil {
		panic(err)
	}
	hostname = fmt.Sprintf("%v", string(b))
	
	ctx.ch <- prometheus.MustNewConstMetric(c.descriptions, prometheus.CounterValue, v, ctx.device.Name, ctx.device.Address, activemacaddress, status, expiresafter, activeaddress, hostname)
}
```

So far, it works fine.

**Comment by hatamiarash7** [comment]
Thank you, that's sounds good. But we have this problem with many other encodes too. As you can see, there are multiple collectors in this project. So how many exception checks should we write to ignore errors? Of course, we must look for an alternative way to solve this problem.

Do you have an opinion?

**Comment by Rid-lin** [comment]
I think it is possible to write a function that automatically decodes from all encodings that are supported by the "golang.org/x/text/encoding" package in UTF-8, but that will require a lot of research.
Therefore, I suggest making a setting in the configuration file, "hostname_encoding" and changing the encoding according to it.
And by default, take the encoding that you like :-).
The main thing is that the characters "\ x8f \ x8a" leave the hostname.
Well, the hostname will not look like User-ПК, but like User-�� or like User-Åè, but the program will continue to work - and this is the most important thing.
