### ISSUE TITLE
The same issue as #1 but in DHCP

### ISSUE THREAD

**Issue by egorsmkv** [hatamiarash7/Mikrotik-Exporter#2]
```
{"level":"info","msg":"Welcome to Mikrotik Prometheus Exporter","time":"2020-07-29T18:42:15Z"}
{"level":"info","msg":"Version: 1.2","time":"2020-07-29T18:42:15Z"}
{"level":"info","msg":"Setting up collector for devices","numDevices":1,"time":"2020-07-29T18:42:15Z"}
{"level":"info","msg":"Listening on :9436","time":"2020-07-29T18:42:15Z"}
panic: label value "Stream-\x8f\x8a" is not valid UTF-8

goroutine 6 [running]:
github.com/prometheus/client_golang/prometheus.MustNewConstMetric(...)
	/root/go/pkg/mod/github.com/prometheus/client_golang@v1.2.1/prometheus/value.go:102
mikrotik-exporter/collector.(*dhcpLeaseCollector).collectMetric(0xc0001281e0, 0xc000162520, 0xc0001b1140)
	/mnt/e/Github/Mikrotik-Exporter/collector/dhcp_lease_collector.go:68 +0x4bd
mikrotik-exporter/collector.(*dhcpLeaseCollector).collect(0xc0001281e0, 0xc000162520, 0x0, 0x0)
	/mnt/e/Github/Mikrotik-Exporter/collector/dhcp_lease_collector.go:40 +0x86
mikrotik-exporter/collector.(*collector).connectAndCollect(0xc0000aeec0, 0xc000182100, 0xc0000ab080, 0x0, 0x0)
	/mnt/e/Github/Mikrotik-Exporter/collector/collector.go:320 +0x14b
mikrotik-exporter/collector.(*collector).collectForDevice(0xc0000aeec0, 0xc0000a4950, 0x6, 0xc0000a4970, 0xe, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/mnt/e/Github/Mikrotik-Exporter/collector/collector.go:291 +0xdc
mikrotik-exporter/collector.(*collector).Collect.func1(0xc0000aeec0, 0xc0000ab080, 0xc0000245d0, 0xc0000a4950, 0x6, 0xc0000a4970, 0xe, 0x0, 0x0, 0x0, ...)
	/mnt/e/Github/Mikrotik-Exporter/collector/collector.go:256 +0x7d
created by mikrotik-exporter/collector.(*collector).Collect
	/mnt/e/Github/Mikrotik-Exporter/collector/collector.go:255 +0x2f2
```

**Comment by egorsmkv** [comment]
#1

**Comment by hatamiarash7** [comment]
You can remove non-english characters to solve the problem.  

I'll prepare an update to ignore UTF-8 errors.

**Comment by egorsmkv** [comment]
I can but it isn't the solution.

**Comment by hatamiarash7** [comment]
@egorsmkv Where did you use this value "Stream-\x8f\x8a" ?

**Comment by egorsmkv** [comment]
It's a name that was provided by the Mikrotik device.

**Comment by hatamiarash7** [comment]
I know that ... But where is it used? This title isn't related to the Mikrotik device and has been applied according to your settings.

It's in **DHCP** / **DHCP leases** settings.

**Comment by egorsmkv** [comment]
Correct. But it's just a name which your program must save somehow or just ignore with a warning to the log/

**Comment by hatamiarash7** [comment]
My dear friend :))) I want to simulate your situation for debugging the project !!!!  

Please tell me where is it used

**Comment by egorsmkv** [comment]
Today I and our sysadmin were trying to find a device with this name “Stream-XXX” in our network but we didn’t find it. 

Maybe it was a mobile device connected to the network via WiFi but we couldn’t find it.

**Comment by hatamiarash7** [comment]
Ok ... I will check it by another way
